import AnimatedText from '@/components/AnimatedText'
import Layout from '@/components/Layout'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import React from 'react'
import { GithubIcon } from '../../public/All-Texts/Icons'
import project1 from '../../public/images/projects/crypto-screener-cover-image.jpg'

const FeaturedProject = ({ type, title, summary, image, link, github }) => {
  return (
    <article className='w-full flex items-center justify-between rounded-3xl border border-solid border-dark bg-light shadow-2xl p-12'>
      <Link href={link} target="_blank" className='w-1/2 cursor-pointer overflow-hidden rounded-lg'>
        <Image src={image} alt={title} className="w-full h-auto" />
      </Link>
      <div className='w-1/2 flex flex-col items-start justify-between pl-6'>
        <span className='text-primary font-medium text-xl'>{type}</span>
        <Link href={link} target="_blank" className='hover:underline underline-offset-2'>
          <h2 className='my-2 w-full text-left text-4xl font-bold'>{title}</h2>
        </Link>
        <p className='my-2 text-dark font-medium'>{summary}</p>
        <div className='mt-2 flex items-center'>
          <Link href={github} target='_blank' className='w-10'><GithubIcon /></Link>
          <Link href={link} target='_blank' className='ml-4 rounded-lg bg-dark text-light p-2 px-6 text-lg font-semibold'>Visit Project</Link>
        </div>
      </div>
    </article>
  )
}
const Project = ({ type, title, summary, image, link, github }) => {
  return (
    <article className='w-full flex flex-col items-center justify-center rounded-2xl border border-solid border-dark bg-light p-6 relative'>
      <Link href={link} target="_blank" className='w-full cursor-pointer overflow-hidden rounded-lg'>
        <Image src={image} alt={title} className="w-full h-auto" />
      </Link>
      <div className='w-full flex flex-col items-start justify-between mt-4'>
        <span className='text-primary font-medium text-xl'>{type}</span>
        <Link href={link} target="_blank" className='hover:underline underline-offset-2'>
          <h2 className='my-2 w-full text-left text-4xl font-bold'>{title}</h2>
        </Link>
        {/* <p className='my-2 text-dark font-medium'>{summary}</p> */}
        <div className='mt-2 flex items-center'>
          <Link href={github} target='_blank' className='w-10'><GithubIcon /></Link>
          <Link href={link} target='_blank' className='ml-4 rounded-lg bg-dark text-light p-2 px-6 text-lg font-semibold'>Visit</Link>
        </div>
      </div>
    </article>
  )
}
const projects = () => {
  return (
    <>
      <Head>
        <title>Abhishek | Projects Page</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className='w-full mb-16 flex flex-col items-center justify-center'>
        <Layout className='pt-16'>
          <AnimatedText text=" Imagination Trumps Knowledge" className='mb-16' />
          <div className='grid grid-col-12 gap-24'>
            <div className='col-span-12'>
              <FeaturedProject
                title="Warehouse Management System"
                type='Featured Project'
                summary='A product of TrackTrans where stocks are handled in each warehouse and can be returned, dispatched, collected or transferred to another warehouse or to the customer with limited access to each accounts for each of the functions.'
                image={project1}
                link='/'
                github='/'
              />
            </div>
            <div className='col-span-6'>
              <Project
                title="Recruitment Portal"
                type='Featured Project'
                summary='A product of TrackTrans where stocks are handled in each warehouse and can be returned, dispatched, collected or transferred to another warehouse or to the customer with limited access to each accounts for each of the functions.'
                image={project1}
                link='/'
                github='/'
              />
            </div>
            <div className='col-span-6'>
              <Project
                title="NTTS"
                type='Featured Project'
                summary='A product of TrackTrans where stocks are handled in each warehouse and can be returned, dispatched, collected or transferred to another warehouse or to the customer with limited access to each accounts for each of the functions.'
                image={project1}
                link='/'
                github='/'
              />
            </div>
            <div className='col-span-6'>
              <Project
                title="Recruitment Portal"
                type='Featured Project'
                summary='A product of TrackTrans where stocks are handled in each warehouse and can be returned, dispatched, collected or transferred to another warehouse or to the customer with limited access to each accounts for each of the functions.'
                image={project1}
                link='/'
                github='/'
              />
            </div>
            <div className='col-span-6'>
              <Project
                title="Recruitment Portal"
                type='Featured Project'
                summary='A product of TrackTrans where stocks are handled in each warehouse and can be returned, dispatched, collected or transferred to another warehouse or to the customer with limited access to each accounts for each of the functions.'
                image={project1}
                link='/'
                github='/'
              />
            </div>
            <div className='col-span-6'>
              <Project
                title="Recruitment Portal"
                type='Featured Project'
                summary='A product of TrackTrans where stocks are handled in each warehouse and can be returned, dispatched, collected or transferred to another warehouse or to the customer with limited access to each accounts for each of the functions.'
                image={project1}
                link='/'
                github='/'
              />
            </div>
          </div>
        </Layout>
      </main>
    </>
  )
}

export default projects